# Generated by Django 6.0.2 on 2026-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_size_alter_product_stock_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_source',
            field=models.CharField(blank=True, help_text='Например: avito_active / avito_archive', max_length=50, null=True, verbose_name='Источник импорта'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_uid',
            field=models.CharField(blank=True, help_text='Уникальный ключ для защиты от дублей при импорте.', max_length=255, null=True, unique=True, verbose_name='UID импорта'),
        ),
    ]
