# Generated by Django 6.0.2 on 2026-02-12 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_import_source_product_import_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлен (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_applied',
            field=models.BooleanField(default=False, verbose_name='Резерв применён'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(choices=[('none', '—'), ('cdek', 'СДЭК'), ('rus_post', 'Почта России'), ('boxberry', 'Boxberry'), ('yandex', 'Яндекс'), ('other', 'Другое')], default='none', max_length=30, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Трек-номер'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Резерв (если нет размеров)'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='reserved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Резерв размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='import_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник импорта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='import_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='UID импорта'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'ordering': ('-changed_at',),
            },
        ),
    ]
