# Generated by Django 6.0.2 on 2026-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_delivered_at_order_reserved_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
