# Generated by Django 6.0.2 on 2026-03-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='label',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
    ]
