# Generated by Django 6.0.2 on 2026-03-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('product', 'label'), 'verbose_name': 'Размер товара', 'verbose_name_plural': 'Размеры товара'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
